'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
     await queryInterface.bulkInsert('Spots', [
      {
         ownerId:1,
         address:"Redmond,WA",
         city:"Redmond",
         state:"WA",
         country:"USA",
         lat:69.21,
         lng:42.43,
         name:"Thenu",
         description:"townhouse",
         price:49.21
       },
       {
        ownerId:2,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:79.21,
        lng:52.43,
        name:"Kalyan",
        description:"townhouse",
        price:78.21
      },
      {
        ownerId:3,
        address:"Bothel,WA",
        city:"Bothel",
        state:"WA",
        country:"USA",
        lat:72.21,
        lng:51.43,
        name:"John",
        description:"Cabin",
        price:57.44
      },
      {
        ownerId:4,
        address:"Snohomish,WA",
        city:"Snohomish",
        state:"WA",
        country:"USA",
        lat:80.21,
        lng:51.43,
        name:"Smith",
        description:"house",
        price:48.21
      },
      {
        ownerId:5,
        address:"Rainier,WA",
        city:"Rainier",
        state:"WA",
        country:"USA",
        lat:89.21,
        lng:82.43,
        name:"Ted",
        description:"townhouse",
        price:58.21
      },
      {
        ownerId:6,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:89.21,
        lng:32.43,
        name:"Phill",
        description:"SingleFamilyhouse",
        price:98.21
      },
      {
        ownerId:7,
        address:"QueenAnne,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:99.21,
        lng:62.43,
        name:"Naren",
        description:"townhouse",
        price:98.21
      },
      {
        ownerId:8,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:89.21,
        lng:62.43,
        name:"Ram",
        description:"townhouse",
        price:58.21
      },
      {
        ownerId:9,
        address:"Kirkland,WA",
        city:"Kirkland",
        state:"WA",
        country:"USA",
        lat:89.21,
        lng:62.43,
        name:"Karthik",
        description:"townhouse",
        price:98.21
      },
      {
        ownerId:10,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:78.21,
        lng:56.43,
        name:"Dhaniya",
        description:"townhouse",
        price:102.21
      },
      {
        ownerId:11,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:89.21,
        lng:59.43,
        name:"Bindhu",
        description:"townhouse",
        price:88.21
      },
      {
        ownerId:12,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:69.21,
        lng:92.43,
        name:"Ruku",
        description:"Cabin",
        price:78.21
      },
      {
        ownerId:13,
        address:"Kent,WA",
        city:"Kent",
        state:"WA",
        country:"USA",
        lat:99.21,
        lng:62.43,
        name:"Diya",
        description:"townhouse",
        price:98.21
      },
      {
        ownerId:14,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:99.21,
        lng:52.43,
        name:"Prasad",
        description:"Mansion",
        price:508.21
      },
      {
        ownerId:15,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:59.21,
        lng:572.43,
        name:"Millie",
        description:"townhouse",
        price:98.21
      },
      {
        ownerId:16,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:89.21,
        lng:62.43,
        name:"Saranya",
        description:"townhouse",
        price:88.21
      },
      {
        ownerId:17,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:79.21,
        lng:52.43,
        name:"Chase",
        description:"townhouse",
        price:89.21
      },
      {
        ownerId:18,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:79.21,
        lng:52.43,
        name:"Foreman",
        description:"townhouse",
        price:45.21
      },
      {
        ownerId:19,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:79.21,
        lng:52.43,
        name:"House",
        description:"townhouse",
        price:98.21
      },
      {
        ownerId:20,
        address:"Seattle,WA",
        city:"Seattle",
        state:"WA",
        country:"USA",
        lat:79.21,
        lng:52.43,
        name:"Cameron",
        description:"townhouse",
        price:89.21
      },
      
      ], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
     await queryInterface.bulkDelete('Spots', null, {});
  }
};
